// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version string
}

type User struct {
	ID             int32
	Username       string
	HashedPassword string
	CreatedAt      pgtype.Timestamptz
}
