// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: segments.sql

package repository

import (
	"context"
)

const insertSegment = `-- name: InsertSegment :exec
insert into "public"."segments" (track_id, geometry) values ($1, $2)
`

type InsertSegmentParams struct {
	TrackID  int32
	Geometry interface{}
}

func (q *Queries) InsertSegment(ctx context.Context, arg InsertSegmentParams) error {
	_, err := q.db.ExecContext(ctx, insertSegment, arg.TrackID, arg.Geometry)
	return err
}
