// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tracks.sql

package repository

import (
	"context"
)

const insertTrack = `-- name: InsertTrack :one
insert into "public"."tracks" (gpxfile_id, type, name) values ($1, $2, $3) returning id
`

type InsertTrackParams struct {
	GpxfileID int32
	Type      Tracktype
	Name      string
}

func (q *Queries) InsertTrack(ctx context.Context, arg InsertTrackParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertTrack, arg.GpxfileID, arg.Type, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}
